replicaCount: 5

namespace:
  name: prod

image:
  repository: paristiz/techtrends
  pullPolicy: IfNotPresent
  tag: "latest"
  # Overrides the image tag whose default is the chart appVersion.

#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

service:
  type: ClusterIP
  port: 7111
  targetPort: 3111 

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111



resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 500m
     memory: 256i
   requests:
     cpu: 350m
     memory: 128Mi
